[2024-09-20T10:17:47.980+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-20T10:17:47.988+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_python_operator.external_python manual__2024-09-20T10:17:43.143240+00:00 [queued]>
[2024-09-20T10:17:47.992+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_python_operator.external_python manual__2024-09-20T10:17:43.143240+00:00 [queued]>
[2024-09-20T10:17:47.993+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-09-20T10:17:47.999+0000] {taskinstance.py:2879} INFO - Executing <Task(ExternalPythonOperator): external_python> on 2024-09-20 10:17:43.143240+00:00
[2024-09-20T10:17:48.011+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=128) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-20T10:17:48.012+0000] {standard_task_runner.py:72} INFO - Started process 132 to run task
[2024-09-20T10:17:48.014+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'example_python_operator', 'external_python', 'manual__2024-09-20T10:17:43.143240+00:00', '--job-id', '15', '--raw', '--subdir', '/home/***/.local/lib/python3.12/site-packages/***/example_dags/example_python_operator.py', '--cfg-path', '/tmp/tmp4r2e45gu']
[2024-09-20T10:17:48.015+0000] {standard_task_runner.py:105} INFO - Job 15: Subtask external_python
[2024-09-20T10:17:48.096+0000] {task_command.py:467} INFO - Running <TaskInstance: example_python_operator.external_python manual__2024-09-20T10:17:43.143240+00:00 [running]> on host e7275b2d8499
[2024-09-20T10:17:48.263+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_python_operator' AIRFLOW_CTX_TASK_ID='external_python' AIRFLOW_CTX_EXECUTION_DATE='2024-09-20T10:17:43.143240+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-20T10:17:43.143240+00:00'
[2024-09-20T10:17:48.265+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-20T10:17:48.265+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-20T10:17:48.265+0000] {logging_mixin.py:190} INFO - Current task name:external_python state:running start_date:2024-09-20 10:17:47.988484+00:00
[2024-09-20T10:17:48.265+0000] {logging_mixin.py:190} INFO - Dag name:example_python_operator and current dag run status:running
[2024-09-20T10:17:48.266+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-20T10:17:48.547+0000] {baseoperator.py:405} WARNING - ExternalPythonOperator.execute cannot be called outside TaskInstance!
[2024-09-20T10:17:48.597+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python /tmp/venv-calli88xg4aa/script.py /tmp/venv-calli88xg4aa/script.in /tmp/venv-calli88xg4aa/script.out /tmp/venv-calli88xg4aa/string_args.txt /tmp/venv-calli88xg4aa/termination.log
[2024-09-20T10:17:48.598+0000] {process_utils.py:190} INFO - Output:
[2024-09-20T10:17:50.075+0000] {process_utils.py:194} INFO - /home/***/.local/lib/python3.12/site-packages/***/plugins_manager.py:30 DeprecationWarning: 'cgitb' is deprecated and slated for removal in Python 3.13
[2024-09-20T10:17:52.231+0000] {process_utils.py:194} INFO - Running task via /home/***/.local/bin/python
[2024-09-20T10:17:52.236+0000] {process_utils.py:194} INFO - Sleeping
[2024-09-20T10:17:52.237+0000] {process_utils.py:194} INFO - Please wait...
[2024-09-20T10:17:53.240+0000] {process_utils.py:194} INFO - Please wait...
[2024-09-20T10:17:54.241+0000] {process_utils.py:194} INFO - Please wait...
[2024-09-20T10:17:55.242+0000] {process_utils.py:194} INFO - Please wait...
[2024-09-20T10:17:56.259+0000] {process_utils.py:194} INFO - Finished
[2024-09-20T10:17:59.051+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-20T10:17:59.357+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-20T10:17:59.364+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=example_python_operator, task_id=external_python, run_id=manual__2024-09-20T10:17:43.143240+00:00, execution_date=20240920T101743, start_date=20240920T101747, end_date=20240920T101759
[2024-09-20T10:17:59.446+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-09-20T10:17:59.451+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-09-20T10:17:59.452+0000] {logging_mixin.py:190} INFO - Dag name:example_python_operator queued_at:2024-09-20 10:17:43.156099+00:00
[2024-09-20T10:17:59.454+0000] {logging_mixin.py:190} INFO - Task hostname:e7275b2d8499 operator:ExternalPythonOperator
[2024-09-20T10:17:59.533+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-20T10:17:59.666+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-20T10:17:59.674+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
